### ISSUE TITLE
Solidity Language Server constantly crashing with Foundry test imports

### ISSUE THREAD

**Issue by yvasilyev92** [NomicFoundation/hardhat-vscode#507]
Version 0.7.3

When importing `.sol` files into a Foundry` .t.sol` test file the Solidity language server begins to crash until it refuses to restart. 
It started with 3 of my `.sol` files triggering the crash, then 2, and now just one even though no changes were made to the files. All .sol files compile just fine, and Foundry tests run against them pass just fine, however when importing them into the `.t.sol` file causes a VScode Failed Request issue followed by the Solidity language server restarting & crashing until the 
**Visual Studio Code: The Solidity Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted** Error appears.

Output result: 

> Solidity by Nomic Foundation Starting ...
[Info  - 12:13:18 PM] env: production
[Info  - 12:13:18 PM] Client starting
[Info  - 12:13:19 PM] Language server starting
[Info  - 12:13:19 PM]   Release: hardhat-solidity@0.7.3
[Info  - 12:13:19 PM]   Environment: production
[Info  - 12:13:19 PM]   Telemetry Enabled: true
[Info  - 12:13:19 PM]   Telemetry Tracking Id: xxx…
[Info  - 12:13:19 PM]   Workspace Folders:
[Info  - 12:13:19 PM]     company (file:///Users/$USER/src/github.com/company)
[Info  - 12:13:19 PM] Fetching latest solidity versions
[Info  - 12:13:19 PM] Language server ready
[Info  - 12:13:20 PM] [indexing] Found projects:
[Info  - 12:13:20 PM] [indexing] -  Type: Hardhat
[Info  - 12:13:20 PM] [indexing]    Base path: /Users/$USER/src/github.com/company/packages/hardhat-ts
[Info  - 12:13:20 PM] [indexing]    Config file: /Users/$USER/src/github.com/company/packages/hardhat-ts/hardhat.config.ts
[Info  - 12:13:20 PM] [indexing] -  Type: Foundry
[Info  - 12:13:20 PM] [indexing]    Base path: /Users/$USER/src/github.com/company/packages/hardhat-ts
[Info  - 12:13:20 PM] [indexing]    Config file: /Users/$USER/src/github.com/company/packages/hardhat-ts/foundry.toml
[Info  - 12:13:20 PM] [indexing] -  Type: Foundry
[Info  - 12:13:20 PM] [indexing]    Base path: /Users/$USER/src/github.com/company/packages/hardhat-ts/node_modules/@mypackage/mysecondpackage
[Info  - 12:13:20 PM] [indexing]    Config file: /Users/$USER/src/github.com/company/packages/hardhat-ts/node_modules/@mypackage/mysecondpackage/foundry.toml
[Info  - 12:13:20 PM] [indexing] Initializing /Users/$USER/src/github.com/company/packages/hardhat-ts/hardhat.config.ts
[Info  - 12:13:24 PM] [hardhat-ts] Local HRE loaded
[Info  - 12:13:24 PM] [indexing] Done /Users/$USER/src/github.com/company/packages/hardhat-ts/hardhat.config.ts
[Info  - 12:13:24 PM] [indexing] Initializing /Users/$USER/src/github.com/company/packages/hardhat-ts/foundry.toml
[Info  - 12:13:24 PM] [indexing] Done /Users/$USER/src/github.com/company/packages/hardhat-ts/foundry.toml
[Info  - 12:13:24 PM] [indexing] Initializing /Users/$USER/src/github.com/company/packages/hardhat-ts/node_modules/@mypackage/mysecondpackage/foundry.toml
[Info  - 12:13:24 PM] [indexing] Done /Users/$USER/src/github.com/company/packages/hardhat-ts/node_modules/@mypackage/mysecondpackage/foundry.toml
[Info  - 12:13:24 PM] [indexing] Scanning workspace folders for sol files
[Info  - 12:13:25 PM] [indexing] Scan complete, 2028 sol files found
[Info  - 12:13:25 PM] [indexing] Analyzing 215 solidity files
[Info  - 12:14:44 PM] Connection to server got closed. Server will restart.
[Error - 12:14:44 PM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:51:7304)
    at Object.dispose (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:56:13906)
    at LanguageClient2.handleConnectionClosed (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:58:11970)
    at LanguageClient2.handleConnectionClosed (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:61:18286)
    at closeHandler (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:58:11571)
    at CallbackList.invoke (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:24:14667)
    at Emitter.fire (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:24:15577)
    at closeHandler (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:25:16138)
    at CallbackList.invoke (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:24:14667)
    at Emitter.fire (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:24:15577)
    at IPCMessageReader.fireClose (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:24:18729)
    at ChildProcess.<anonymous> (/Users/$USER/.vscode/extensions/nomicfoundation.hardhat-solidity-0.7.3/out/extension.js:51:17231)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1121:16)
    at Socket.<anonymous> (node:internal/child_process:479:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14)

Re-installing the extension didnt help, re-installing VSCode also didnt help.

**Comment by kanej** [comment]
Hey @yvasilyev92, is the repo you were working on open source to help us reproduce the issue?

**Comment by kanej** [comment]
Closing for now. If we get more information we will reopen.
